# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hour', models.TimeField(auto_now_add=True)),
                ('comment', models.TextField(null=True)),
                ('who_add_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Standard'), (2, 'Comfort'), (3, 'ComfortPlus'), (4, 'VIP')])),
                ('description', models.TextField()),
                ('allowed_type_of_order', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'awaria'), (2, 'wypadek'), (3, 'auto szyba'), (4, 'auto opony')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_plate_number', models.CharField(max_length=16)),
                ('car_first_registration', models.DateTimeField()),
                ('insurance_activ', models.BooleanField()),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistance.Car')),
            ],
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hour', models.TimeField(auto_now_add=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('plate_number', models.CharField(max_length=16, null=True)),
                ('notifier_first_name', models.CharField(max_length=64, null=True)),
                ('notifier_last_name', models.CharField(max_length=256, null=True)),
                ('type_of_order', models.IntegerField(choices=[(1, 'awaria'), (2, 'wypadek'), (3, 'auto szyba'), (4, 'auto opony')], null=True)),
                ('place_car_stay', models.TextField(null=True)),
                ('place_car_target', models.TextField(null=True)),
                ('place_car_rented', models.TextField(null=True)),
                ('status_order', models.IntegerField(choices=[(1, 'Zgłoszenie kompletne'), (2, 'Odmowa'), (3, 'Rezygnacja klienta'), (4, 'Zakończone')], null=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assistance.Comments')),
                ('person_insured', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistance.Insured')),
                ('who_add', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateField(null=True)),
                ('hour_start', models.TimeField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('hour_end', models.TimeField(null=True)),
                ('type_of_task', models.IntegerField(choices=[(1, 'Holowanie'), (2, 'Naprawa na miejscu'), (3, 'Samochód zastępczy'), (4, 'Transport osób'), (5, 'Wymiana szyby'), (6, 'Wymiana opon'), (7, 'Inne (opisz)')], null=True)),
                ('provider', models.TextField()),
                ('provider_phone_number', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=256)),
                ('status_task', models.IntegerField(choices=[(1, 'Zlecone'), (2, 'Anulowane'), (3, 'Wykonane')])),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistance.NewOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=256)),
                ('address_street', models.CharField(max_length=256, null=True)),
                ('address_city', models.CharField(max_length=256, null=True)),
                ('address_post_code', models.CharField(max_length=256, null=True)),
                ('company', models.CharField(max_length=256, null=True)),
                ('nip_company', models.CharField(max_length=32, null=True)),
                ('insurance_company', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='insured',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistance.Person'),
        ),
        migrations.AddField(
            model_name='insured',
            name='type_of_insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistance.InsuranceType'),
        ),
    ]
