# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='phone_number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
