# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0002_auto_20180419_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtask',
            name='provider_email',
            field=models.EmailField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='newtask',
            name='provider_phone_number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
