# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0003_auto_20180419_0642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
