# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0004_auto_20180419_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neworder',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assistance.NewOrder'),
        ),
    ]
