# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0005_auto_20180420_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtask',
            name='rented_car_class',
            field=models.IntegerField(choices=[(1, 'Klasa A'), (2, 'Klasa B'), (3, 'Klasa C'), (4, 'Klasa D'), (5, 'Klasa premium'), (6, 'SUV'), (7, 'Inne')], null=True),
        ),
    ]
