# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0007_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_in_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
