# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0009_auto_20180421_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='type_of_doc',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
