# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistance', '0010_documents_type_of_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtask',
            name='who_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
